//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.1026
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Name_Maze
{
	public class God : MonoBehaviour
	{
		private string Name;
		private int Level;
		private float exp;
		private bool isbought;
		private SpriteRenderer God_Image;
		public God ()
		{
		}
	}
}

